<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/osmformat.proto

namespace OSMReader;

use Google\Protobuf\Internal\GPBUtil;
use OSMReader\GPBMetadata\Proto\Osmformat;

/**
 * Group of OSMPrimitives. All primitives in a group must be the same type.
 *
 * Generated from protobuf message <code>OSMReader.PrimitiveGroup</code>
 */
class PrimitiveGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .OSMReader.Node nodes = 1;</code>
     */
    private $nodes;
    /**
     * Generated from protobuf field <code>.OSMReader.DenseNodes dense = 2;</code>
     */
    private $dense = null;
    /**
     * Generated from protobuf field <code>repeated .OSMReader.Way ways = 3;</code>
     */
    private $ways;
    /**
     * Generated from protobuf field <code>repeated .OSMReader.Relation relations = 4;</code>
     */
    private $relations;
    /**
     * Generated from protobuf field <code>repeated .OSMReader.ChangeSet changesets = 5;</code>
     */
    private $changesets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type \OSMReader\Node[]|\Google\Protobuf\Internal\RepeatedField $nodes
     * @type \OSMReader\DenseNodes $dense
     * @type \OSMReader\Way[]|\Google\Protobuf\Internal\RepeatedField $ways
     * @type \OSMReader\Relation[]|\Google\Protobuf\Internal\RepeatedField $relations
     * @type \OSMReader\ChangeSet[]|\Google\Protobuf\Internal\RepeatedField $changesets
     * }
     */
    public function __construct($data = NULL)
    {
        Osmformat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.Node nodes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.Node nodes = 1;</code>
     * @param \OSMReader\Node[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Node::class);
        $this->nodes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OSMReader.DenseNodes dense = 2;</code>
     * @return \OSMReader\DenseNodes
     */
    public function getDense()
    {
        return $this->dense;
    }

    /**
     * Generated from protobuf field <code>.OSMReader.DenseNodes dense = 2;</code>
     * @param \OSMReader\DenseNodes $var
     * @return $this
     */
    public function setDense($var)
    {
        GPBUtil::checkMessage($var, DenseNodes::class);
        $this->dense = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.Way ways = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWays()
    {
        return $this->ways;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.Way ways = 3;</code>
     * @param \OSMReader\Way[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWays($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Way::class);
        $this->ways = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.Relation relations = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRelations()
    {
        return $this->relations;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.Relation relations = 4;</code>
     * @param \OSMReader\Relation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRelations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Relation::class);
        $this->relations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.ChangeSet changesets = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChangesets()
    {
        return $this->changesets;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMReader.ChangeSet changesets = 5;</code>
     * @param \OSMReader\ChangeSet[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChangesets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, ChangeSet::class);
        $this->changesets = $arr;

        return $this;
    }

}

