<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/osmformat.proto

namespace OSMProto;

if (false) {
    /**
     * This class is deprecated. Use OSMReader\Relation\MemberType instead.
     * @deprecated
     */
    class Relation_MemberType
    {
    }
}
class_exists(Relation\MemberType::class);
@trigger_error('OSMReader\Relation_MemberType is deprecated and will be removed in the next major release. Use OSMReader\Relation\MemberType instead', E_USER_DEPRECATED);

