<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/osmformat.proto

namespace OsmProto;

use Exception;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use OsmProto\GPBMetadata\Osmformat;

/**
 ** String table, contains the common strings in each block.
 *Note that we reserve index '0' as a delimiter, so the entry at that
 *index in the table is ALWAYS blank and unused.
 *
 * Generated from protobuf message <code>OSMReader.StringTable</code>
 */
class StringTable extends Message
{
    /**
     * Generated from protobuf field <code>repeated bytes s = 1;</code>
     */
    private $s;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string[]|RepeatedField $s
     * }
     */
    public function __construct($data = NULL)
    {
        Osmformat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes s = 1;</code>
     * @return RepeatedField
     */
    public function getS()
    {
        return $this->s;
    }

    /**
     * Generated from protobuf field <code>repeated bytes s = 1;</code>
     * @param string[]|RepeatedField $var
     * @return $this
     * @throws Exception
     */
    public function setS($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->s = $arr;

        return $this;
    }

}

