<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/osmformat.proto

namespace OSMProto;

use Google\Protobuf\Internal\GPBUtil;
use OSMProto\GPBMetadata\Osmformat;

/**
 * Generated from protobuf message <code>OSMReader.Way</code>
 */
class Way extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Parallel arrays.
     *
     * Generated from protobuf field <code>repeated uint32 keys = 2 [packed = true];</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>repeated uint32 vals = 3 [packed = true];</code>
     */
    private $vals;
    /**
     * Generated from protobuf field <code>.OSMReader.Info info = 4;</code>
     */
    private $info = null;
    /**
     * DELTA coded
     *
     * Generated from protobuf field <code>repeated sint64 refs = 8 [packed = true];</code>
     */
    private $refs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int|string $id
     * @type int[]|\Google\Protobuf\Internal\RepeatedField $keys
     *           Parallel arrays.
     * @type int[]|\Google\Protobuf\Internal\RepeatedField $vals
     * @type Info $info
     * @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $refs
     *           DELTA coded
     * }
     */
    public function __construct($data = NULL)
    {
        Osmformat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     * @throws \Exception
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Parallel arrays.
     *
     * Generated from protobuf field <code>repeated uint32 keys = 2 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Parallel arrays.
     *
     * Generated from protobuf field <code>repeated uint32 keys = 2 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @throws \Exception
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 vals = 3 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVals()
    {
        return $this->vals;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 vals = 3 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @throws \Exception
     */
    public function setVals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->vals = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OSMReader.Info info = 4;</code>
     * @return Info
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>.OSMReader.Info info = 4;</code>
     * @param Info $var
     * @return $this
     * @throws \Exception
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, Info::class);
        $this->info = $var;

        return $this;
    }

    /**
     * DELTA coded
     *
     * Generated from protobuf field <code>repeated sint64 refs = 8 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRefs()
    {
        return $this->refs;
    }

    /**
     * DELTA coded
     *
     * Generated from protobuf field <code>repeated sint64 refs = 8 [packed = true];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @throws \Exception
     */
    public function setRefs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::SINT64);
        $this->refs = $arr;

        return $this;
    }

}

