<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fileformat.proto

namespace OSMPBF;

use Google\Protobuf\Internal\GPBUtil;

class BlobHeader extends \Google\Protobuf\Internal\Message
{
    private $type = '';
    private $indexdata = '';
    private $datasize = 0;

    public function __construct($data = NULL)
    {
        \GPBMetadata\Proto\Fileformat::initOnce();
        parent::__construct($data);
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    public function getIndexdata()
    {
        return $this->indexdata;
    }

    public function setIndexdata($var)
    {
        GPBUtil::checkString($var, False);
        $this->indexdata = $var;

        return $this;
    }

    public function getDatasize()
    {
        return $this->datasize;
    }

    public function setDatasize($var)
    {
        GPBUtil::checkInt32($var);
        $this->datasize = $var;

        return $this;
    }
}