<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/osmformat.proto

namespace OSMProto\Relation;

/**
 * OSMProto type <code>OSMReader.Relation.MemberType</code>
 */
class MemberType
{
    /**
     * Generated from protobuf enum <code>NODE = 0;</code>
     */
    const NODE = 0;
    /**
     * Generated from protobuf enum <code>WAY = 1;</code>
     */
    const WAY = 1;
    /**
     * Generated from protobuf enum <code>RELATION = 2;</code>
     */
    const RELATION = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MemberType::class, \Relation_MemberType::class);

