<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fileformat.proto

namespace OsmProto\GPBMetadata;

use Google\Protobuf\Internal\DescriptorPool;

class Fileformat
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9010a1670726f746f2f66696c65666f726d61742e70726f746f12084f" .
            "736d50726f746f226c0a04426c6f62120b0a0372617718012001280c1210" .
            "0a087261775f73697a6518022001280512110a097a6c69625f6461746118" .
            "032001280c12110a096c7a6d615f6461746118042001280c121f0a134f42" .
            "534f4c4554455f627a6970325f6461746118052001280c42021801223f0a" .
            "0a426c6f62486561646572120c0a047479706518012001280912110a0969" .
            "6e6465786461746118022001280c12100a086461746173697a6518032001" .
            "2805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

