<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/osmformat.proto

namespace OSMReader;

use Google\Protobuf\Internal\GPBUtil;
use OSMReader\GPBMetadata\Proto\Osmformat;

/**
 ** String table, contains the common strings in each block.
 *Note that we reserve index '0' as a delimiter, so the entry at that
 *index in the table is ALWAYS blank and unused.
 *
 * Generated from protobuf message <code>OSMReader.StringTable</code>
 */
class StringTable extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes s = 1;</code>
     */
    private $s;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string[]|\Google\Protobuf\Internal\RepeatedField $s
     * }
     */
    public function __construct($data = NULL)
    {
        Osmformat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes s = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getS()
    {
        return $this->s;
    }

    /**
     * Generated from protobuf field <code>repeated bytes s = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setS($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->s = $arr;

        return $this;
    }

}

